# --------------------------------------------------------------------
# - spreadsheet          dataframe in .tsv format                    -
# - phenotype            dataframe in .tsv format                    -
# --------------------------------------------------------------------
#spreadsheet_name_full_path: ../data/spreadsheets/TEST_1_gene_expression.tsv
#phenotype_name_full_path:   ../data/spreadsheets/TEST_1_phenotype.tsv

spreadsheet_name_full_path: {{ spreadsheet_name_full_path }}
phenotype_name_full_path:   {{ phenotype_name_full_path }}

# --------------------------------------------------------------------
# - directory where the result files will be written                 -
# --------------------------------------------------------------------
#results_directory:          ./run_dir/results

results_directory:          {{ results_directory }}

# --------------------------------------------------------------------
# - taxon id as a string                                             -
# - source_hint as a string                                          -
# - pipeline type indicates which pipeline to clean                  -
# - input_data_type indicates which pipelines to clean up            -
# --------------------------------------------------------------------
#taxonid:                    '9606'                      # taxon id of a given gene name
#source_hint:                ''                          # hint of looking up ensembl name in Redis database
#pipeline_type:              gene_priorization_pipeline  # valid pipeline names:
                                                        # gene_priorization_pipeline,
                                                        # samples_clustering_pipeline,
                                                        # geneset_characterization_pipeline,
                                                        # gene_prioritization

taxonid:                    {{ taxon_id }}
source_hint:                '{{ source_hint }}'
pipeline_type:              {{ pipeline_type }}

# --------------------------------------------------------------------
# - Redis database credentials                                       -
# --------------------------------------------------------------------
redis_credential:                                       # knoweng Redis database credentials
                            #host: knowredis.knowhub.org
                            #password: KnowEnG
                            #port: 6380

                            host: '{{ redis_host }}'
                            password: '{{ redis_pass }}'
                            port: '{{ redis_port }}'
