apiVersion: batch/v1
kind: Job
metadata:
  name: dc-test
spec:
  template:
    metadata:
      name: dc-test
    spec:
      containers:
      - name: data-cleanup
#        image: knowengdev/data-cleanup_pipeline:04_17_2017
        image: bodom0015/data-cleanup
        env:

        - name: CORRELATION_MEASURE
          value: "pearson"

        - name: SPREADSHEET_NAME_FULL_PATH
          value: "../data/spreadsheets/TEST_1_gene_expression.tsv"

        - name: PHENOTYPE_NAME_FULL_PATH
          value: "../data/spreadsheets/TEST_1_phenotype_pearson.tsv"

        - name: RESULTS_DIRECTORY
          value: "./run_dir/results"

        - name: TAXON_ID
          value: "9606"

        - name: SOURCE_HINT
          value: ""

        - name: PIPELINE_TYPE
          value: "gene_prioritization_pipeline"

        - name: REDIS_HOST
          value: "localhost"
#          value: "10.254.5.109"

        - name: REDIS_PASS
          value: ""

        - name: REDIS_PORT
          value: "6379"

        volumeMounts:
        - mountPath: /home/test/run_dir
          name: rundir
      volumes:
      - name: rundir
        hostPath:
          path:  /var/glfs/global/jobs/data-cleanup/
      restartPolicy: Never
