apiVersion: v1
kind: ReplicationController
metadata:
  name: efs-explorer
spec:
  replicas: 1
  selector:
    component: efs-explorer
  template:
    metadata:
      labels:
        component: efs-explorer
    spec:
      hostNetwork: true
      containers:
      - name: efs-explorer
        imagePullPolicy: Always
        image: ubuntu:16.04
        stdin: true
        tty: true
        workingDir: "/efs/"
        volumeMounts:
        - name: efs-pvc
          mountPath: "/efs/"
      volumes:
      - name: efs-pvc
        persistentVolumeClaim:
          claimName: efs
