apiVersion: batch/v1
kind: Job
metadata:
  name: gp-test
spec:
  parallelism: 2
  template:
    metadata:
      name: gp-test
    spec:
      containers:
      - name: gene-prioritization
#        image: knowengdev/gene_prioritization_pipeline:04_26_2017
        image: bodom0015/gene-prioritization
        env:

        # ANALYSIS_METHOD=[correlation|net_correlation|bootstrap_correlation|bootstrap_net_correlation]
        - name: ANALYSIS_METHOD
#          value: "{{ analysis_method }}"
          value: "bootstrap_net_correlation"

        # CORRELATION_METHOD=[pearson|t_test]
        - name: CORRELATION_METHOD
#          value: "{{ correlation_method }}"
          value: "pearson"

        # Path and file name of the 4 col network file
        - name: GG_NETWORK_NAME_FULL_PATH
#          value: "{{ gg_network_name_full_path }}"
          value: "../data/networks/TEST_1_gene_gene.edge"

        # Path and file name of user supplied gene sets (aka "features file")
        - name: SPREADSHEET_NAME_FULL_PATH
#          value: "{{ spreadsheet_name_full_path }}"
          value: "../data/spreadsheets/TEST_1_gene_sample.tsv"

        # Path and file name of user supplied phenotype response file (aka "response file")
        - name: PHENOTYPE_NAME_FULL_PATH
#          value: "{{ phenotype_name_full_path }}"
          value: "../data/spreadsheets/TEST_multi_drug_response_pearson.txt"

        # Directory where the result and temporary files will be written
        - name: RESULTS_DIRECTORY
#          value: "{{ results_directory }}"
          value: "./run_dir/results"

        # Number of random samplings
        - name: NUMBER_OF_BOOTSTRAPS
#          value: "{{ number_of_bootstraps }}"
          value: "10"

        # Select 90% of spreadsheet columns
        - name: COLS_SAMPLING_FRACTION
#          value: "{{ cols_sampling_fraction }}"
          value: "0.9"

        # Maximum number of iterations without convergence in random walk with restart
        - name: RWR_MAX_ITERATIONS
#          value: "{{ rwr_max_iterations }}"
          value: "100"

        # Frobenius norm tolerance of spreadsheet vector in random walk
        - name: RWR_CONVERGENCE_TOLERANCE
#          value: "{{ rwr_convergence_tolerance }}"
          value: "1.0e-2"

        # Restart probability in random walk: alpha in V_(n+1) = alpha * N * Vn + (1-alpha) * Vo
        - name: RWR_RESTART_PROBABILITY
#          value: "{{ rwr_restart_probability }}"
          value: "0.5"       

        # Number of top genes selected
        - name: TOP_BETA_OF_SORT
#          value: "{{ top_beta_of_sort }}"
          value: "3"

        volumeMounts:
        - mountPath: /home/test/run_dir
          name: rundir
      volumes:
      - name: rundir
        hostPath:
          path:  /var/glfs/global/jobs/gene-prioritization/
      restartPolicy: Never
